/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package igtools.gui2;

import igtools.common.nucleotide.B3Nucleotide;
import igtools.common.sequence.B3LLSequence;
import igtools.dictionaries.elsa.NELSA;
import igtools.streams.BufferedFASTANucleotideStream;
import igtools.streams.INucleotideStream;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author vbonnici
 */
public class WSSequenceEditDialog extends javax.swing.JDialog{

    
    private WSSequence seq = null;
    private boolean answer = false;
    
    private String prevB3seqFile = "";
    private String prevNELSAFile = "";
    
    
    /**
     * Creates new form WSSequenceEditDialog
     */
    public WSSequenceEditDialog(java.awt.Frame parent, boolean modal, WSSequence seq) {
        super(parent, modal);
        initComponents();
        
        this.seq = seq;
        this.nameField.setText(seq.getName());
        this.fastaField.setText(seq.getFASTAFile());
        this.b3seqField.setText(seq.getB3seqFile());
        this.nelsaField.setText(seq.getNELSAFile());
    }
    
    
    public boolean getAnswer(){
        return answer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nelsaField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        b3seqField = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        fastaField = new javax.swing.JTextField();
        nameField = new javax.swing.JTextField();
        okButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nelsaBrowse = new javax.swing.JButton();
        fastaBrowse = new javax.swing.JButton();
        b3Browse = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(453, 240));
        getContentPane().setLayout(new java.awt.FlowLayout());

        jLabel1.setText("Sequence");

        jLabel5.setText("FASTA");

        jLabel4.setText("NELSA");

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        nameField.setText("new sequence name");
        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        okButton.setText("Ok");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("3bit");

        jLabel2.setText("Name");

        nelsaBrowse.setText("Browse");
        nelsaBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nelsaBrowseActionPerformed(evt);
            }
        });

        fastaBrowse.setText("Browse");
        fastaBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fastaBrowseActionPerformed(evt);
            }
        });

        b3Browse.setText("Browse");
        b3Browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3BrowseActionPerformed(evt);
            }
        });

        jButton1.setText("Generate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Generate");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nelsaField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(b3seqField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fastaField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(nelsaBrowse)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(b3Browse)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1)))
                                .addGap(1, 1, 1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(fastaBrowse)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cancelButton)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(14, 14, 14)
                        .addComponent(nameField)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fastaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(fastaBrowse))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b3seqField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b3Browse)
                            .addComponent(jButton1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nelsaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(nelsaBrowse)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancelButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void fastaBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fastaBrowseActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setMultiSelectionEnabled(false);
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int returnVal = chooser.showOpenDialog(this);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            //seq.setFASTAFile(chooser.getSelectedFile().getAbsolutePath());
            this.fastaField.setText(chooser.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_fastaBrowseActionPerformed

    private void b3BrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3BrowseActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setMultiSelectionEnabled(false);
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int returnVal = chooser.showOpenDialog(this);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            //seq.setB3seqFile(chooser.getSelectedFile().getAbsolutePath());
            this.b3seqField.setText(chooser.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_b3BrowseActionPerformed

    private void nelsaBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nelsaBrowseActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setMultiSelectionEnabled(false);
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int returnVal = chooser.showOpenDialog(this);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            //seq.setNELSAFile(chooser.getSelectedFile().getAbsolutePath());
            this.nelsaField.setText(chooser.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_nelsaBrowseActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        if(this.nameField.getText().trim().length() != 0){
            answer = true;
            
            seq.setName(this.nameField.getText().trim());
            
            if(this.fastaField.getText().trim().length() == 0){
                seq.setFASTAFile(null);
            }
            else{
                seq.setFASTAFile(this.fastaField.getText().trim());
            }
            
            
            if(this.nelsaField.getText().trim().length() == 0){
                seq.setNELSA(null);
                seq.setNELSAFile(null);
            }
            else{
                if(prevNELSAFile == null  ||   prevNELSAFile.compareTo(this.nelsaField.getText().trim())!=0){
                    seq.setNELSAFile(this.nelsaField.getText().trim());
                    seq.setNELSA(null);
                }
            }
            
            
            if(this.b3seqField.getText().trim().length() == 0){
                seq.setB3seq(null);
                seq.setB3seqFile(null);
            }
            else{
                if(prevB3seqFile == null  ||   prevB3seqFile.compareTo(this.b3seqField.getText().trim())!=0){
                    seq.setB3seqFile(this.b3seqField.getText().trim());
                    seq.setB3seq(null);
                }
            }
            
            this.dispose();
        }
        else{
            this.nameField.setText("insert a valid name");
        }
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        answer = false;
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // generate 3bit seq
        String iseq = this.fastaField.getText();
        File f = new File(iseq);
        if(iseq.trim().length()==0 && !(f.exists() && f.isFile())){
            JOptionPane.showMessageDialog(this, "FASTA file is not valid.", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        else{
            try{
                String oseq = iseq+".3bit";
                    INucleotideStream<B3Nucleotide> fastaStream = new BufferedFASTANucleotideStream(iseq);
                    //while(fastaStream.next()!=null);
                    while(fastaStream.nextCode() != INucleotideStream.NULL_CODE);
                    System.out.println("sequence length " + (fastaStream.position()));
                    B3LLSequence bitgenome = new B3LLSequence(fastaStream.position() + 1);
                    fastaStream.close();
                    fastaStream = new BufferedFASTANucleotideStream(iseq);
                    bitgenome.fillBy(fastaStream);
                    fastaStream.close();
                    System.out.println("done");
                    System.out.println("saving...");
                    bitgenome.save(oseq);
                    System.out.println("done");
                    
                    this.b3seqField.setText(oseq);
            }catch(Exception e){
                    JOptionPane.showMessageDialog(this, "En error occurred during conversion to 3bit.\n"+e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
                    System.out.println(e);
                    e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // generate nelsa
        String iseq = this.b3seqField.getText();
        File f = new File(iseq);
        if(iseq.trim().length()==0 && !(f.exists() && f.isFile())){
            JOptionPane.showMessageDialog(this, "3bit file is not valid.", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        else{
            try{
                String o_file = iseq.replace(".3bit", "") + ".nelsa";
                System.out.println("reading 3bit seq...");
                B3LLSequence b3seq = B3LLSequence.load(iseq);
                System.out.println("done");
                System.out.println("building nelsa...");
                NELSA nelsa = new NELSA(b3seq);
                System.out.println("done");
                System.out.println("saving...");
                nelsa.save(o_file);
                System.out.println("done");
                this.nelsaField.setText(o_file);
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, "En error occurred during NELSA generation.\n"+e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
                System.out.println(e);
		e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b3Browse;
    private javax.swing.JTextField b3seqField;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton fastaBrowse;
    private javax.swing.JTextField fastaField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField nameField;
    private javax.swing.JButton nelsaBrowse;
    private javax.swing.JTextField nelsaField;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables


}
