/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package igtools.gui2.dictionaries;

import igtools.common.sequence.B3LLSequence;
import igtools.common.sequence.B3Sequence;
import igtools.common.util.Timer;
import igtools.dictionaries.elsa.IELSAIterator;
import igtools.dictionaries.elsa.INELSA;
import igtools.dictionaries.elsa.NELSA;
import igtools.gui2.WSSequence;
import igtools.gui2.codistances.*;
import igtools.gui2.mults.CoMultFrame;
import java.awt.BorderLayout;
import java.awt.Color;
import java.io.File;
import java.text.DecimalFormat;
import java.util.Map;
import java.util.TreeMap;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartMouseEvent;
import org.jfree.chart.ChartMouseListener;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.entity.XYItemEntity;
import org.jfree.chart.plot.Plot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.plot.XYPlot;
import org.jfree.chart.renderer.xy.StandardXYBarPainter;
import org.jfree.chart.renderer.xy.XYBarRenderer;
import org.jfree.data.xy.XYDataItem;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author vbonnici
 */
public class KDictsSizesFrame extends javax.swing.JFrame {
     private static void usage(){
        System.out.println("Usage: cmd isequence.b3seq  inelsa.nelsa");
    }
    
    
    
    private DecimalFormat df = new DecimalFormat("###,###,###,###");
    
    private WSSequence wsseq;
    private NELSA nelsa;
    private int pickedK = 0;

    /**
     * Creates new form ProperCoDistancesFrame
     */
    public KDictsSizesFrame(WSSequence wsseq) {
        this.wsseq = wsseq;
        this.nelsa = wsseq.getNELSA();
        
        initComponents();
        this.setTitle("Dictionary size trends: "+wsseq.getName());
       
        center_panel.setLayout(new BorderLayout());
        this.pickedPairLabel.setText("");
        this.comultButton.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fromKField = new javax.swing.JTextField();
        toKField = new javax.swing.JTextField();
        drawButton = new javax.swing.JButton();
        pickedPairLabel = new javax.swing.JLabel();
        comultButton = new javax.swing.JButton();
        center_panel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 350));

        fromKField.setColumns(4);
        fromKField.setText("6");

        toKField.setColumns(4);
        toKField.setText("20");

        drawButton.setText("draw");
        drawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawButtonActionPerformed(evt);
            }
        });

        pickedPairLabel.setText("jLabel1");

        comultButton.setText("co-mult");
        comultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comultButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fromKField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toKField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(drawButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 272, Short.MAX_VALUE)
                .addComponent(pickedPairLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comultButton)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fromKField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toKField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(drawButton)
                    .addComponent(pickedPairLabel)
                    .addComponent(comultButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        center_panel.setBackground(new java.awt.Color(254, 254, 254));
        center_panel.setPreferredSize(new java.awt.Dimension(600, 300));

        javax.swing.GroupLayout center_panelLayout = new javax.swing.GroupLayout(center_panel);
        center_panel.setLayout(center_panelLayout);
        center_panelLayout.setHorizontalGroup(
            center_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        center_panelLayout.setVerticalGroup(
            center_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 297, Short.MAX_VALUE)
        );

        getContentPane().add(center_panel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void drawButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drawButtonActionPerformed
        makeChart();
    }//GEN-LAST:event_drawButtonActionPerformed

    private void comultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comultButtonActionPerformed
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CoMultFrame frame = new CoMultFrame(wsseq, pickedK);
                frame.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                frame.setVisible(true);
                frame.makeChart();
            }
        });
    }//GEN-LAST:event_comultButtonActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel center_panel;
    private javax.swing.JButton comultButton;
    private javax.swing.JButton drawButton;
    private javax.swing.JTextField fromKField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel pickedPairLabel;
    private javax.swing.JTextField toKField;
    // End of variables declaration//GEN-END:variables

    
    
    
    
    private void makeChart(){
        if(this.nelsa != null){
            pickedPairLabel.setText("");
            comultButton.setEnabled(false);
            center_panel.removeAll();
            center_panel.setBackground(Color.RED);
            center_panel.invalidate();
            center_panel.repaint();
            
           try{
        
                int from_k = Integer.parseInt(fromKField.getText());
                int to_k = Integer.parseInt(toKField.getText());

                if(from_k > to_k){
                    int tmp = to_k;
                    to_k = from_k;
                    from_k = tmp;
                }


                final Map<Integer,Integer> sizes = new TreeMap<>();


                for(int k=from_k; k<=to_k; k++){
                    IELSAIterator it = nelsa.begin(k);

                    int count = 0;
                    while(it.next()){
                        count++;
                    }

                    sizes.put(k, count);
                }





                final XYSeries series = new XYSeries("");
                for(Map.Entry<Integer, Integer> entry : sizes.entrySet()){
                    System.out.println(entry.getKey() +"\t"+ entry.getValue());
                    series.add(entry.getKey(), entry.getValue());
                }


        //        System.out.println("["+it.istart()+","+it.iend()+"]");
                final XYSeriesCollection dataset = new XYSeriesCollection(series);


                final JFreeChart chart = ChartFactory.createXYBarChart(
                                                null, 
                                                "k", 
                                                false, 
                                                "Dictionary size", 
                                                dataset, 
                                                PlotOrientation.VERTICAL, 
                                                false, 
                                                true, 
                                                false);
                
//                final JFreeChart chart  = ChartFactory.createXYLineChart(
//                    "",
//                    "k", 
//                    "Dictionary size", 
//                    dataset,
//                    PlotOrientation.VERTICAL,
//                    false,
//                    true,
//                    false
//                );

                final ChartPanel chartPanel = new ChartPanel(chart);
                chartPanel.setPreferredSize(center_panel.getPreferredSize());
                chart.setBackgroundPaint(Color.white);
                //chartPanel.setMouseZoomable(false);
                chartPanel.setMouseWheelEnabled(true);

                chartPanel.setMinimumDrawWidth( 0 );
                chartPanel.setMinimumDrawHeight( 0 );
                chartPanel.setMaximumDrawWidth( 1920 );
                chartPanel.setMaximumDrawHeight( 1200 );

                XYPlot plot = (XYPlot) chart.getPlot();
                plot.setBackgroundPaint(Color.WHITE);
                ((XYBarRenderer) plot.getRenderer()).setBarPainter(new StandardXYBarPainter());
                plot.getRenderer().setSeriesPaint( 0, Color.BLUE);
                
                ((XYBarRenderer) plot.getRenderer()).setMargin(0.1);
                
                
                plot.setDomainPannable(true);
                plot.setRangePannable(true);
                
                plot.setDomainGridlinesVisible(true);  
                plot.setRangeGridlinesVisible(true);  
                plot.setRangeGridlinePaint(Color.gray);  
                plot.setDomainGridlinePaint(Color.gray);
                


                chartPanel.addChartMouseListener(new ChartMouseListener() {

                    @Override
                    public void chartMouseClicked(ChartMouseEvent cme) {

                        Plot p = cme.getChart().getPlot();
                        if(p instanceof XYPlot){                    
                            if(cme.getEntity() instanceof XYItemEntity){                        
                                int seriesIndex = ((XYItemEntity)cme.getEntity()).getSeriesIndex();
                                int item = ((XYItemEntity)cme.getEntity()).getItem();
                                XYSeries series = ((XYSeriesCollection)dataset).getSeries(seriesIndex);
                                XYDataItem xyItem = series.getDataItem(item);
                                System.out.println(xyItem);
                                
                                pickedK = xyItem.getX().intValue();
                                pickedPairLabel.setText("("+df.format(xyItem.getX().intValue())+" ; "+df.format(xyItem.getY().intValue())+")");
                                comultButton.setEnabled(true);
                                
                                return;
                            }
                        }
                        
                        pickedK = 0;
                        pickedPairLabel.setText("");
                        comultButton.setEnabled(false);
                    }

                    @Override
                    public void chartMouseMoved(ChartMouseEvent cme) {
                    }

                });
        
        
                center_panel.add(chartPanel, BorderLayout.CENTER);
                center_panel.revalidate();
                center_panel.repaint();
        
           }catch(Exception e){
               
           }
        }
    }
    
}
