/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package igtools.gui2.wordList;

import igtools.common.nucleotide.B3Nucleotide;
import igtools.common.sequence.B3Sequence;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;

/**
 *
 * @author vbonnici
 */
public class WLFlatViewPanel extends javax.swing.JPanel {

    private final static Color[] colors = {
        Color.blue,         //0     A,
        Color.red,          //1     C
        Color.green,        //2     G
        Color.yellow,       //3     T
        Color.black        //4     N
    };
    private final static Color backgroundColor = Color.white;
    
    
    private B3Sequence seq;
    private int[] start;
    private int[] end;
    
    private int ikmer = 0;
    
    private int nW = 4, nH = 1;
    private int leftOffset = 10;
    private int prefW = 200, prefH = 200;
    private int dPrefH = 200;
    
    
    public WLFlatViewPanel(B3Sequence seq, int[] start, int[] end){
        this.seq = seq;
        this.start = start;
        this.end = end;
        
        prefSize();
    }
    
    public void setData(int nW, int nH){
        this.nW = nW;
        this.nH = nH;
    }
    
    public void prefSize(){
        prefW =leftOffset + ((end[0]-start[0]) * nW);
        prefH = end[0] * nH;
        
        this.setSize(new Dimension(prefW,dPrefH));
        this.setMinimumSize(new Dimension(prefW,dPrefH));
        this.setMaximumSize(new Dimension(prefW,prefH));
        this.setPreferredSize(new Dimension(prefW,dPrefH));
        
        this.revalidate();
    }
        
    
    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        
        

        g.setColor(backgroundColor);
        g.fillRect(0, 0, this.getWidth(), this.getHeight());
        
        int x = leftOffset, y = 0;
        
        
        
        //char[] cs;
        for(int i=ikmer; i<start.length; i++){
            //cs = kmers[i].toCharArray();
            //System.out.println(B3Nucleotide.toString(kmers[i]));
        	//System.out.println("["+start[i]+","+end[i]+"]");
            
            x = leftOffset;
            //for(int j=0; j<cs.length; j++){
            if(seq.getB3(start[i])<0 || seq.getB3(start[i])>3){
            	g.setColor(colors[ 4 ]);
            	for(int j=start[i]; j<end[i]; j++){
            		g.fillRect(x, y, nW, nH);
	                x += nW;
            	}
            }
            else{
            
	            for(int j=start[i]; j<end[i]; j++){
	                g.setColor(colors[  seq.getB3(j) ]);
	                g.fillRect(x, y, nW, nH);
	                x += nW;
	            }
            }
            
            y += nH;
            if(y>this.getHeight())
                break;
        }
        
    }
    
    
    
    public int rowCount(){
        return this.getHeight() / nH;
    }
    
    public void up(int step){
        if(ikmer > 0){
            ikmer -= step;
            if(ikmer < 0)
                ikmer = 0;
            this.repaint();
        }
    }
    
    public void down(int step){
        ikmer += step;
        if(ikmer >= start.length - (this.getHeight()/nH)){
            ikmer = (start.length - 1) - (this.getHeight()/nH);
            if(ikmer < 0)
                ikmer = 0;
        }
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
